### PR TITLE
include Smclint/Ssclint/Smclic/Ssclic/Smaia/Ssaia as valid options to constants.py

### PR DESCRIPTION
**Pull request by dansmathers**
For issue: https://github.com/riscv-software-src/riscv-config/issues/133
updated constants.py to included Smclint/Ssclint/Smclic/Ssclic/Smaia/Ssaia as valid S_extensions

### CODE REVIEW

**Comment by neelgala** [comment]
@dansmathers Could you please list out with links to the spec versions you are refering to for this PR ?

Since `'Smclic','Ssclic','Smaia','Ssaia'` specs introduce/modify CSRs to the spec, this PR should include those CSR updates as well.

A quick way forward would be to include just the `'Smclint','Ssclint'` since they don't introduce any CSRs

Things you need to do anyhow:
1. install bumpversion using `pip install bumpversion`
2. run `bumpversion --no-tag --config-file setup.cfg minor`. (this should change the version everywhere to 3.10.0)
3.  create an Entry in the CHANGELOG.md for 3.10.0 and highlight the changes done

It would be great if you could update the "Deploying" section in CONTRIBUTING.rst with what you feel will help other contributors as well (ignore if its a bother)

**Comment by neelgala** [comment]
@dansmathers riscv-config already has support for indexed registers (since debug uses them a lot). 
You can look at the [tdata schema](https://github.com/riscv-software-src/riscv-config/blob/master/riscv_config/schemas/schema_debug.yaml#L168-L229) for reference. An example of how these are used is provided in the example [here](https://github.com/riscv-software-src/riscv-config/blob/master/examples/rv64i_debug.yaml#L44-L78)

The docs obviously need to be updated for this new type of register which I will push as a new PR

**Comment by dansmathers** [comment]
I guess I need help.  I tried following the CONTRIBUTING.rst and when I tried git push origin add_smclint, I got this message:

Username for 'https://github.com': <user>
Password for 'https://<user>@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/riscv-software-src/riscv-config.git/'

Any way I can do this from the gui?  gui pulls, issues, etc. seem to work fine.

**Comment by dansmathers** [comment]
I guess it closed when I tried to update my branch with the latest.  reopening.

**Pull request closed without merging**
