### PR TITLE
Add Zmmul as new (sub)extension of the M-extension

### PR DESCRIPTION
**Pull request by allenjbaum**
Adds Zmmul as a valid ISA string, and checks that you can't have both M-extension and Zmmul at the same time

### CODE REVIEW

**Comment by Imperas** [comment]
I read latest spec: The RISC-V Instruction Set Manual Volume I: Unprivileged ISA May 4, 2021
and it has no mention of Zmmul???
Surely riscv-config should only include a) things in formal specs, and b) really on ratified things...
 - or it ends up just being random checks...
Simon

**Comment by Imperas** [comment]
pls post a link to the spec of this Zmmul as it is not easily found

**Comment by allenjbaum** [comment]
It will be sent out for review more broadly but the short answer is:

This extension defines instructions comprising M-extension unprivileged
spec section 8.:
    MUL, MULH, MUHU and MULHSU
and (for RV64/RV128)
    MULW
without section 8.2 of the M-extension: DIV* or REM* instructions.  No
other architectural state is changed.

**Comment by Imperas** [comment]
Ah - ok it is a private edit for some new idea that has not yet been written down publicly.
Which working groups email list or meeting is it being discussed in?
When will it make the ISA spec draft?]thnx,
Simon

**Comment by allenjbaum** [comment]
Should be going out for public review soon. Has been reviewed by a few
people already, including the chairs of priv and Unpriv (unpriv is what it
belongs to, really).
This will be a fast track extension because it isn't really anything new,
just assigning a name/arch-string to an existing set of ops. No new state,
no new tests, no new ops, no new mnemonics, no new semantics.

**Comment by pdonahue-ventana** [comment]
https://lists.riscv.org/g/tech-unprivileged/topic/proposal_zmmul_draft/81580347

**Comment by Imperas** [comment]
Thank you for the link. Simon

**Comment by neelgala** [comment]
Zmmul is already part of the upstream branch. closing this PR.

**Pull request closed without merging**
