### PR TITLE
add support for zicbo* extensions

### PR DESCRIPTION
**Pull request by liweiwei90**
This patch add support for cmo extensions with related part of Xenvcfg CSRs.

### CODE REVIEW

**Comment by pdonahue-ventana** [comment]
The cache block size for Zicboz may be different than the cache block size for Zicbom and Zicbop.  There should be a way to specify two separate values.

@dkruckemyer-ventana

**Comment by neelgala** [comment]
@liweiwei90 in the description of the `cache_block_size` please mention the units wether its bits or bytes, etc. 

Since this is an optional Z-extension the field you have defined should not be a "required" field. Can we default to 0 instead of 64 to indicate that this field is not set/used by the DUT?

Addressing @pdonahue-ventana comments the following may be a possible solution:
```yaml
    zicbo_cache_block_sz:
     type: dict
     schema:
       zicbomp_sz:
          type: integer
          max: [4096]
          default: 0
          check_with: cache_block_size
       zicbob_sz:
          type: integer
          max: [4096]
          default: 0
          check_with: cache_block_size
```

**Comment by liweiwei90** [comment]
OK. I'll update this later. However, I don't quite understand why there are two kind of cache block size.

**Comment by pawks** [comment]
Also I think the node should go into the platform yaml rather than the isa yaml.

**Comment by liweiwei90** [comment]
> Also I think the node should go into the platform yaml rather than the isa yaml.

OK. The dict type of  zicbo_cache_block_sz will trigger fault when  check_isa_specs.

**Pull request merged**
