### PR TITLE
Isa regex improvements issue 104

### PR DESCRIPTION
**Pull request by tovine**
These are my suggested changes as discussed in #104

### CODE REVIEW

**Comment by tovine** [comment]
I realize this change will affect the other PRs that add Z extensions, but changes should be relatively minor and easier to do once this has been merged (if it's accepted as currently proposed, with the new Z extension list)

**Comment by neelgala** [comment]
This looks really good. Thanks for the PR. 

I think a 32-bit implementation can support both I and E base extensions (which are runtime mutually exclusive). So the ISA string RV32IE should be a legal string as well - which your current solution does not parse correctly. Could you fix that ?

Also I will need you to run [bumpversion](https://github.com/riscv-software-src/riscv-config/blob/master/CONTRIBUTING.rst#deploying) to change the versions by a `minor` upgrade and also make an entry in the Changelog.md file.

**Comment by neelgala** [comment]
> I think a 32-bit implementation can support both I and E base extensions (which are runtime mutually exclusive). So the ISA string RV32IE should be a legal string as well - which your current solution does not parse correctly. Could you fix that ?
> 
Looks like your assumption for keeping I and E exclusive is indeed valid : https://github.com/riscv/riscv-isa-manual/issues/894. You can ignore my suggestion there.

**Comment by tovine** [comment]
Done, does it look ok?
I saw that you mentioned on the tech-config mailing list that the doc is sligtly outdated (about using isa_validator.py instead of SchemaValidator.py), if you want we could probably also add that change to this PR and get it done at the same time.

Though if there are more changes than simply replacing references to SchemaValidator with isa_validator then it should probably be done separately. I'll leave the decision up to you. :)

**Review by neelgala — APPROVED** [review]

**Pull request merged**
